# @package _global_
dataset:
  coeff: 3.0

model:
  encoder:
    optimizer:
      learning_rate: 0.001
    batch_size: 64
    seq_hidden_units: 24
    br_size: 24
    fc_hidden_units: 96
    dropout_rate: 0.2

  train_decoder: True
  decoder:
    optimizer:
      learning_rate: 0.01
    batch_size: 256
    br_size: 18
    fc_hidden_units: 9
    dropout_rate: 0.1

exp:
  weights_ema: False
  balancing: grad_reverse